#!/bin/sh -e

if [ ! -h src/github.com/javouhey/seneca ]; then
	mkdir -p src/github.com/javouhey/
	ln -s ../../.. src/github.com/javouhey/seneca
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}

VERSION=$(cat ./VERSION)
GITSHA=$(git rev-parse HEAD)
LDFLAGS='-X main.GitSHA "'$GITSHA'" -X main.Version "'$VERSION'" -w'

echo "installing seneca to $GOBIN"
go install -ldflags "$LDFLAGS" github.com/javouhey/seneca
