#!/bin/sh -e

if [ ! -h src/github.com/javouhey/seneca ]; then
	mkdir -p src/github.com/javouhey/
	ln -s ../../.. src/github.com/javouhey/seneca
fi

export GOBIN=${PWD}/bin
export GOPATH=${PWD}

go install -v github.com/javouhey/seneca
