#!/bin/sh -e

export GOBIN=${PWD}/bin
export GOPATH=${PWD}

echo ${PWD}
if [ -f ${PWD}/bin/seneca ] 
then
  rm -I ${PWD}/bin/seneca
fi 
find ${PWD}/pkg -name "*.a" | xargs rm
go clean -x github.com/javouhey/seneca
