#!/bin/sh -e

export GOBIN=${PWD}/bin
export GOPATH=${PWD}

echo "${GOPATH}"

# Avoid because it does it for 3rd party & vendored libs
#go vet ./...
go tool vet -all=false -shadow=true -assign=true -v=false -unreachable=true -test=false -composites=false ./io
go vet -x ./util ./progress
