#!/bin/sh -e

export GOBIN=${PWD}/bin
export GOPATH=${PWD}

echo "${GOPATH}"

# Avoid because it does it for 3rd party & vendored libs
#go vet ./...
go tool vet -all=false -shadow=true -assign=true -v=false -unreachable=true -composites=false io/*.go

go vet -x github.com/javouhey/seneca/io
go vet -x github.com/javouhey/seneca/util
go vet -x github.com/javouhey/seneca/progress
